version: "3.5"

services:
  postgres:
    container_name: surface-database
    image: timescale/timescaledb-postgis:2.3.0-pg13
    restart: unless-stopped
    env_file:
      - api/production.env
    volumes:
      - ./:/app
      - database-volume:/var/lib/postgresql/data
      - ./data/shared:/data/shared
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

  api:
    build:
      dockerfile: Dockerfile
      context: api
    container_name: surface-api
    command: wait-for-it postgres:5432 -- python manage.py runserver 0.0.0.0:8000 --settings=tempestas_api.settings
    env_file:
      - api/production.env
    restart: unless-stopped
    volumes:
      - ./api:/surface
      - ./data/media:/data/media
      - ./data/shared:/data/shared
      - ./data/documents:/data/documents
    ports:
      - "8080:8000"
    depends_on:
      - postgres
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"

volumes:
  database-volume:
    driver: local
